/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ravindu
 */
public class addResults extends javax.swing.JFrame {

    /**
     * Creates new form addResults
     */
    String subjects[] = {"0","0","0","0","0","0","0"};
    public addResults() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mark6txt = new javax.swing.JTextField();
        mark7txt = new javax.swing.JTextField();
        sub1txt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        gotID = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sub2txt = new javax.swing.JTextField();
        sub3txt = new javax.swing.JTextField();
        sub4txt = new javax.swing.JTextField();
        sub5txt = new javax.swing.JTextField();
        sub6txt = new javax.swing.JTextField();
        sub7txt = new javax.swing.JTextField();
        mark1txt = new javax.swing.JTextField();
        mark2txt = new javax.swing.JTextField();
        mark3txt = new javax.swing.JTextField();
        mark4txt = new javax.swing.JTextField();
        mark5txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        yearcombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        semcombo = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(mark6txt);
        mark6txt.setBounds(301, 376, 90, 20);
        getContentPane().add(mark7txt);
        mark7txt.setBounds(301, 429, 90, 20);
        getContentPane().add(sub1txt);
        sub1txt.setBounds(18, 133, 190, 20);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        gotID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gotID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(705, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gotID)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 870, 30);

        jButton2.setText("home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(669, 373, 103, 23);

        jLabel1.setText("Subject");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(48, 94, 60, 14);

        jLabel2.setText("payment (Rs.)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(311, 94, 80, 14);

        sub2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub2txtActionPerformed(evt);
            }
        });
        getContentPane().add(sub2txt);
        sub2txt.setBounds(18, 179, 190, 20);
        getContentPane().add(sub3txt);
        sub3txt.setBounds(18, 226, 190, 20);
        getContentPane().add(sub4txt);
        sub4txt.setBounds(18, 273, 190, 20);
        getContentPane().add(sub5txt);
        sub5txt.setBounds(18, 325, 190, 20);
        getContentPane().add(sub6txt);
        sub6txt.setBounds(18, 376, 190, 20);
        getContentPane().add(sub7txt);
        sub7txt.setBounds(18, 429, 190, 20);
        getContentPane().add(mark1txt);
        mark1txt.setBounds(301, 133, 90, 20);
        getContentPane().add(mark2txt);
        mark2txt.setBounds(301, 179, 90, 20);
        getContentPane().add(mark3txt);
        mark3txt.setBounds(301, 226, 90, 20);
        getContentPane().add(mark4txt);
        mark4txt.setBounds(301, 273, 90, 20);
        getContentPane().add(mark5txt);
        mark5txt.setBounds(301, 325, 90, 20);

        jLabel5.setText("Student ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(555, 105, 52, 14);
        getContentPane().add(idtxt);
        idtxt.setBounds(660, 102, 164, 20);

        jLabel3.setText("Academic year");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 150, 80, 14);

        yearcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(yearcombo);
        yearcombo.setBounds(660, 150, 160, 20);

        jLabel4.setText("Semester");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(554, 210, 70, 14);

        semcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        getContentPane().add(semcombo);
        semcombo.setBounds(660, 210, 170, 20);

        jButton3.setText("Add marks");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(660, 330, 120, 23);

        jButton1.setText("Show Subjects");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(660, 290, 111, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        

        String id= idtxt.getText();
        String year = yearcombo.getSelectedItem().toString();
        String sem = semcombo.getSelectedItem().toString();
        
        

        try {
            String sql = "Select subjectID from subjectselection where StudentID = ? and subjectID like ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, id);
            stm.setObject(2,"%"+year+sem+"%");

            ResultSet rs = stm.executeQuery();
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
            if(rs.next()){
                //System.out.println(rs.getString("subjectID"));
                sub1txt.setText(rs.getString("subjectID"));
            }
            if(rs.next()){
                //subjects[1] = rs.getString("subjectID");
                sub2txt.setText(rs.getString("subjectID"));
            }
            if(rs.next()){
                //subjects[2] = rs.getString("subjectID");
                sub3txt.setText(rs.getString("subjectID"));
            }
            if(rs.next()){
                //subjects[3] = rs.getString("subjectID");
                sub4txt.setText(rs.getString("subjectID"));
            }
            if(rs.next()){
                //subjects[4] = rs.getString("subjectID");
                sub5txt.setText(rs.getString("subjectID"));
            }
            if(rs.next()){
                //subjects[5] = rs.getString("subjectID");
                sub6txt.setText(rs.getString("subjectID"));
            }
            if(rs.next()){
                //subjects[6] = rs.getString("subjectID");
                sub7txt.setText(rs.getString("subjectID"));
            }

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        
        

        

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        paymentInfo frame = new paymentInfo();
        home p = new home();
        p.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sub2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub2txtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String mark1 = mark1txt.getText();
        String mark2 = mark2txt.getText();
        String mark3 = mark3txt.getText();
        String mark4 = mark4txt.getText();
        String mark5 = mark5txt.getText();
        String mark6 = mark6txt.getText();
        String mark7 = mark7txt.getText();
        
        try {
            String sql = "update subjectselection set examMarks = ? where StudentID = ? and subjectID = ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, mark1);
            stm.setObject(2, idtxt.getText());
            stm.setObject(3, sub1txt.getText());
            
            int rs = stm.executeUpdate();
            if(rs>0){
                
            }
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        try {
            String sql = "update subjectselection set examMarks = ? where StudentID = ? and subjectID = ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, mark2);
            stm.setObject(2, idtxt.getText());
            stm.setObject(3, sub2txt.getText());
            
            int rs = stm.executeUpdate();
            if(rs>0){
                
            }
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        try {
            String sql = "update subjectselection set examMarks = ? where StudentID = ? and subjectID = ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, mark3);
            stm.setObject(2, idtxt.getText());
            stm.setObject(3, sub3txt.getText());
            
            int rs = stm.executeUpdate();
            if(rs>0){
                
            }
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        try {
            String sql = "update subjectselection set examMarks = ? where StudentID = ? and subjectID = ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, mark4);
            stm.setObject(2, idtxt.getText());
            stm.setObject(3, sub4txt.getText());
            
            int rs = stm.executeUpdate();
            if(rs>0){
                
            }
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        try {
            String sql = "update subjectselection set examMarks = ? where StudentID = ? and subjectID = ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, mark5);
            stm.setObject(2, idtxt.getText());
            stm.setObject(3, sub5txt.getText());
            
            int rs = stm.executeUpdate();
            if(rs>0){
                
            }
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        try {
            String sql = "update subjectselection set examMarks = ? where StudentID = ? and subjectID = ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, mark6);
            stm.setObject(2, idtxt.getText());
            stm.setObject(3, sub6txt.getText());
            
            int rs = stm.executeUpdate();
            if(rs>0){
                
            }
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        try {
            String sql = "update subjectselection set examMarks = ? where StudentID = ? and subjectID = ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, mark7);
            stm.setObject(2, idtxt.getText());
            stm.setObject(3, sub7txt.getText());
            
            int rs = stm.executeUpdate();
            if(rs>0){
                JOptionPane.showMessageDialog(this, "Added Successfully");
            }
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
                
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel gotID;
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mark1txt;
    private javax.swing.JTextField mark2txt;
    private javax.swing.JTextField mark3txt;
    private javax.swing.JTextField mark4txt;
    private javax.swing.JTextField mark5txt;
    private javax.swing.JTextField mark6txt;
    private javax.swing.JTextField mark7txt;
    private javax.swing.JComboBox semcombo;
    private javax.swing.JTextField sub1txt;
    private javax.swing.JTextField sub2txt;
    private javax.swing.JTextField sub3txt;
    private javax.swing.JTextField sub4txt;
    private javax.swing.JTextField sub5txt;
    private javax.swing.JTextField sub6txt;
    private javax.swing.JTextField sub7txt;
    private javax.swing.JComboBox yearcombo;
    // End of variables declaration//GEN-END:variables
}
