/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;
import javax.swing.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JList;

/**
 *
 * @author Ravindu
 */
public class courseRegPostgraduate extends javax.swing.JFrame {

    /**
     * Creates new form courseRegPostgraduate
     */
    String comArr[] = {"0","0","0"};
    String opArr[] = {"0","0","0","0","0","0"};
    public static boolean x;
    public courseRegPostgraduate() {
        initComponents();
        yeartxt.setVisible(false);
        numtxt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enrollCombo = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cs1txt = new javax.swing.JLabel();
        cs2txt = new javax.swing.JLabel();
        cs3txt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        os1txt = new javax.swing.JRadioButton();
        os2txt = new javax.swing.JRadioButton();
        os3txt = new javax.swing.JRadioButton();
        os4txt = new javax.swing.JRadioButton();
        os5txt = new javax.swing.JRadioButton();
        os6txt = new javax.swing.JRadioButton();
        sem1button = new javax.swing.JButton();
        sem2button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        IDtxt = new javax.swing.JTextField();
        facCombo = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        yeartxt = new javax.swing.JTextField();
        numtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        courseCombo.setSelectedItem(null);
        courseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboActionPerformed(evt);
            }
        });

        enrollCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "February", "July" }));
        enrollCombo.setSelectedItem(null);
        enrollCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollComboActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Postgraduate");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(676, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jLabel1.setText("Student ID");

        jLabel2.setText("Enrollment");

        jLabel3.setText("Faculty");

        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Compulsory Subjects");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Optional Subjects (Select upto 4)");

        os1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                os1txtActionPerformed(evt);
            }
        });

        os2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                os2txtActionPerformed(evt);
            }
        });

        os4txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                os4txtActionPerformed(evt);
            }
        });

        os5txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                os5txtActionPerformed(evt);
            }
        });

        os6txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                os6txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(os3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(os6txt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(os2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(os5txt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cs2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cs1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cs3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(os1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(os4txt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(cs1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cs2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cs3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(os1txt)
                            .addComponent(os4txt))
                        .addGap(18, 18, 18)
                        .addComponent(os2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(os5txt))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(os6txt)
                    .addComponent(os3txt))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        sem1button.setText("Select Subjects Semester 1");
        sem1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem1buttonActionPerformed(evt);
            }
        });

        sem2button.setText("Select Subjects Semester 2");
        sem2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem2buttonActionPerformed(evt);
            }
        });

        jLabel4.setText("Course");

        facCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Business", "Computing", "Engineering" }));
        facCombo.setSelectedItem(null);
        facCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facComboActionPerformed(evt);
            }
        });

        jButton3.setText("Register");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(76, 76, 76)
                                .addComponent(numtxt)
                                .addGap(120, 120, 120))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(36, 36, 36)
                                        .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(53, 53, 53)
                                        .addComponent(facCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(38, 38, 38)
                                        .addComponent(enrollCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(54, 54, 54)
                                        .addComponent(courseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sem1button, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(yeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(sem2button, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1))
                            .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3))
                            .addComponent(facCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(enrollCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4))
                            .addComponent(courseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(sem1button)
                        .addGap(7, 7, 7)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(sem2button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(yeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enrollComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollComboActionPerformed
        if ("July".equals(enrollCombo.getSelectedItem())){
            sem1button.setVisible(true);
        }
        else{
            sem1button.setVisible(true);
            sem2button.setVisible(true);
        }
    }//GEN-LAST:event_enrollComboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String id = IDtxt.getText();
        String os1 ;
        String os2 ;
        String os3 ;
        String os4 ;
        String os5 ;
        String os6 ;
        yeartxt.setText("1");
        numtxt.setText("1");

        String cs1 = comArr[0];
        String cs2 = comArr[1];
        String cs3 = comArr[2];

        try{
            String sql = "Insert into subjectselection(StudentID,subjectID) values(?,?),(?,?),(?,?)";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, id);
            stm.setObject(2, cs1);
            stm.setObject(3, id);
            stm.setObject(4, cs2);
            stm.setObject(5, id);
            stm.setObject(6, cs3);
            int res = stm.executeUpdate();
            if(res>0){
                JOptionPane.showMessageDialog(this, "Added Successfully");
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        if(os1txt.isSelected()){
            os1 = opArr[0];
            try{
                String sql = "Insert into subjectselection(StudentID,subjectID) values(?,?)";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
                PreparedStatement stm = conn.prepareStatement(sql);
                stm.setObject(1, id);
                stm.setObject(2, os1);

                int res = stm.executeUpdate();
                if(res>0){

                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if(os2txt.isSelected()){
            os2 = opArr[1];
            try{
                String sql = "Insert into subjectselection(StudentID,subjectID) values(?,?)";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
                PreparedStatement stm = conn.prepareStatement(sql);
                stm.setObject(1, id);
                stm.setObject(2, os2);

                int res = stm.executeUpdate();
                if(res>0){

                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if(os3txt.isSelected()){
            os3 = opArr[2];
            try{
                String sql = "Insert into subjectselection(StudentID,subjectID) values(?,?)";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
                PreparedStatement stm = conn.prepareStatement(sql);
                stm.setObject(1, id);
                stm.setObject(2, os3);

                int res = stm.executeUpdate();
                if(res>0){

                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if(os4txt.isSelected()){
            os4 = opArr[3];
            try{
                String sql = "Insert into subjectselection(StudentID,subjectID) values(?,?)";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
                PreparedStatement stm = conn.prepareStatement(sql);
                stm.setObject(1, id);
                stm.setObject(2, os4);

                int res = stm.executeUpdate();
                if(res>0){

                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if(os5txt.isSelected()){
            os5 = opArr[4];
            try{
                String sql = "Insert into subjectselection(StudentID,subjectID) values(?,?)";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
                PreparedStatement stm = conn.prepareStatement(sql);
                stm.setObject(1, id);
                stm.setObject(2, os5);

                int res = stm.executeUpdate();
                if(res>0){

                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if(os6txt.isSelected()){
            os6 = opArr[5];
            try{
                String sql = "Insert into subjectselection(StudentID,subjectID) values(?,?)";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
                PreparedStatement stm = conn.prepareStatement(sql);
                stm.setObject(1, id);
                stm.setObject(2, os6);

                int res = stm.executeUpdate();
                if(res>0){

                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }

        //stm.setObject(8, sub.getType());
        //stm.setObject(9, sub.getFacID());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void os1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_os1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_os1txtActionPerformed

    private void os2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_os2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_os2txtActionPerformed

    private void os4txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_os4txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_os4txtActionPerformed

    private void os5txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_os5txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_os5txtActionPerformed

    private void os6txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_os6txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_os6txtActionPerformed

    private void sem1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem1buttonActionPerformed
        jPanel2.setVisible(true);
        String id = IDtxt.getText();
        String fac = facCombo.getSelectedItem().toString();
        String enroll = enrollCombo.getSelectedItem().toString();
        String course = courseCombo.getSelectedItem().toString();
        String a = course.substring(0, 4);
        int i;

        try {
            String sql = "Select subjectID,subjectName from subjects where subjectID like ? and Type = ? and semNo = ? and semYear = ?";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, a+"%");
            stm.setObject(2, "compulsory");
            stm.setObject(3,1);
            stm.setObject(4,"1st year");
            ResultSet rs = stm.executeQuery();
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
            if(rs.next()){
                cs1txt.setText(rs.getString("subjectName"));
                comArr[0] = rs.getString("subjectID");
            }
            if(rs.next()){
                cs2txt.setText(rs.getString("subjectName"));
                comArr[1] = rs.getString("subjectID");
            }
            if(rs.next()){
                cs3txt.setText(rs.getString("subjectName"));
                comArr[2] = rs.getString("subjectID");
            }

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        try {
            String sql = "Select subjectID,subjectName from subjects where subjectID like ? and Type = ? and semNo = ?";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, a+"%");
            stm.setObject(2, "optional");
            stm.setObject(3,1);
            ResultSet rs2 = stm.executeQuery();
            //String x = "cs"+i+"txt";
            if(rs2.next()){
                os1txt.setText(rs2.getString("subjectName"));
                opArr[0] = rs2.getString("subjectID");
            }
            if(rs2.next()){
                os2txt.setText(rs2.getString("subjectName"));
                opArr[1] = rs2.getString("subjectID");
            }
            if(rs2.next()){
                os3txt.setText(rs2.getString("subjectName"));
                opArr[2] = rs2.getString("subjectID");
            }
            if(rs2.next()){
                os4txt.setText(rs2.getString("subjectName"));
                opArr[3] = rs2.getString("subjectID");
            }
            if(rs2.next()){
                os5txt.setText(rs2.getString("subjectName"));
                opArr[4] = rs2.getString("subjectID");
            }
            if(rs2.next()){
                os6txt.setText(rs2.getString("subjectName"));
                opArr[5] = rs2.getString("subjectID");
            }

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_sem1buttonActionPerformed

    private void sem2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem2buttonActionPerformed
        os1txt.setSelected(false);
        os2txt.setSelected(false);
        os3txt.setSelected(false);
        os4txt.setSelected(false);
        os5txt.setSelected(false);
        os6txt.setSelected(false);

        jPanel2.setVisible(true);
        //jPanel2.revalidate();
        //jPanel2.repaint();
        String id = IDtxt.getText();
        String fac = facCombo.getSelectedItem().toString();
        String enroll = enrollCombo.getSelectedItem().toString();
        String course = courseCombo.getSelectedItem().toString();
        String a = course.substring(0, 4);
        int i;

        try {
            String sql = "Select subjectID,subjectName from subjects where subjectID like ? and Type = ? and semNo = ? and semYear = ?";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, a+"%");
            stm.setObject(2, "compulsory");
            stm.setObject(3,2);
            stm.setObject(4,"1st year");
            ResultSet rs = stm.executeQuery();
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
            if(rs.next()){
                cs1txt.setText(rs.getString("subjectName"));
                comArr[0] = rs.getString("subjectID");
            }
            if(rs.next()){
                cs2txt.setText(rs.getString("subjectName"));
                comArr[1] = rs.getString("subjectID");
            }
            if(rs.next()){
                cs3txt.setText(rs.getString("subjectName"));
                comArr[2] = rs.getString("subjectID");
            }

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        try {
            String sql = "Select subjectID,subjectName from subjects where subjectID like ? and Type = ? and semNo = ?";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, a+"%");
            stm.setObject(2, "optional");
            stm.setObject(3,2);
            ResultSet rs2 = stm.executeQuery();
            //String x = "cs"+i+"txt";
            if(rs2.next()){
                os1txt.setText(rs2.getString("subjectName"));
                opArr[0] = rs2.getString("subjectID");
            }
            if(rs2.next()){
                os2txt.setText(rs2.getString("subjectName"));
                opArr[1] = rs2.getString("subjectID");
            }
            if(rs2.next()){
                os3txt.setText(rs2.getString("subjectName"));
                opArr[2] = rs2.getString("subjectID");
            }
            if(rs2.next()){
                os4txt.setText(rs2.getString("subjectName"));
                opArr[3] = rs2.getString("subjectID");
            }
            if(rs2.next()){
                os5txt.setText(rs2.getString("subjectName"));
                opArr[4] = rs2.getString("subjectID");
            }
            if(rs2.next()){
                os6txt.setText(rs2.getString("subjectName"));
                opArr[5] = rs2.getString("subjectID");
            }

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_sem2buttonActionPerformed

    private void facComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facComboActionPerformed
        final DefaultComboBoxModel mode1 = new DefaultComboBoxModel(new String[]{"SCP1-MSc in Computer Science","SCP2-MSc in information Technology"});
        final DefaultComboBoxModel mode2 = new DefaultComboBoxModel(new String[]{"SBP1-MBA(Business Administration)","SBP2-MSc in Applied Finance"});
        final DefaultComboBoxModel mode3 = new DefaultComboBoxModel(new String[]{"SEP1-MSc in Civil Engineering","SEP2-MSc in Mechanical Engineering"});

        facCombo.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                if ("Computing".equals(facCombo.getSelectedItem())){
                    courseCombo.setModel(mode1);
                } else if("Business".equals(facCombo.getSelectedItem())) {
                    courseCombo.setModel(mode2);
                }
                else{
                    courseCombo.setModel(mode3);
                }
            }
        });
    }//GEN-LAST:event_facComboActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String id = IDtxt.getText();
        String os1 ;
        String os2 ;
        String os3 ;
        String os4 ;
        String os5 ;
        String os6 ;

        String cs1 = comArr[0];
        String cs2 = comArr[1];
        String cs3 = comArr[2];

        try{
            String sql = "Insert into subjectselection(StudentID,subjectID) values(?,?),(?,?),(?,?)";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, id);
            stm.setObject(2, cs1);
            stm.setObject(3, id);
            stm.setObject(4, cs2);
            stm.setObject(5, id);
            stm.setObject(6, cs3);
            int res = stm.executeUpdate();
            if(res>0){
                JOptionPane.showMessageDialog(this, "Added Successfully");
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        if(os1txt.isSelected()){
            os1 = opArr[0];
            try{
                String sql = "Insert into subjectselection(StudentID,subjectID) values(?,?)";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
                PreparedStatement stm = conn.prepareStatement(sql);
                stm.setObject(1, id);
                stm.setObject(2, os1);

                int res = stm.executeUpdate();
                if(res>0){

                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if(os2txt.isSelected()){
            os2 = opArr[1];
            try{
                String sql = "Insert into subjectselection(StudentID,subjectID) values(?,?)";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
                PreparedStatement stm = conn.prepareStatement(sql);
                stm.setObject(1, id);
                stm.setObject(2, os2);

                int res = stm.executeUpdate();
                if(res>0){

                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if(os3txt.isSelected()){
            os3 = opArr[2];
            try{
                String sql = "Insert into subjectselection(StudentID,subjectID) values(?,?)";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
                PreparedStatement stm = conn.prepareStatement(sql);
                stm.setObject(1, id);
                stm.setObject(2, os3);

                int res = stm.executeUpdate();
                if(res>0){

                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if(os4txt.isSelected()){
            os4 = opArr[3];
            try{
                String sql = "Insert into subjectselection(StudentID,subjectID) values(?,?)";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
                PreparedStatement stm = conn.prepareStatement(sql);
                stm.setObject(1, id);
                stm.setObject(2, os4);

                int res = stm.executeUpdate();
                if(res>0){

                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if(os5txt.isSelected()){
            os5 = opArr[4];
            try{
                String sql = "Insert into subjectselection(StudentID,subjectID) values(?,?)";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
                PreparedStatement stm = conn.prepareStatement(sql);
                stm.setObject(1, id);
                stm.setObject(2, os5);

                int res = stm.executeUpdate();
                if(res>0){

                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if(os6txt.isSelected()){
            os6 = opArr[5];
            try{
                String sql = "Insert into subjectselection(StudentID,subjectID) values(?,?)";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
                PreparedStatement stm = conn.prepareStatement(sql);
                stm.setObject(1, id);
                stm.setObject(2, os6);

                int res = stm.executeUpdate();
                if(res>0){

                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void courseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //dispose();
        //courseRegPostgraduate frame = new courseRegPostgraduate();
        paymentInfo p = new paymentInfo();
        p.setVisible(true);
        x = true;
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(courseRegPostgraduate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(courseRegPostgraduate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(courseRegPostgraduate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(courseRegPostgraduate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new courseRegPostgraduate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField IDtxt;
    private final javax.swing.JComboBox courseCombo = new javax.swing.JComboBox();
    private javax.swing.JLabel cs1txt;
    private javax.swing.JLabel cs2txt;
    private javax.swing.JLabel cs3txt;
    private javax.swing.JComboBox enrollCombo;
    private javax.swing.JComboBox facCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField numtxt;
    private javax.swing.JRadioButton os1txt;
    private javax.swing.JRadioButton os2txt;
    private javax.swing.JRadioButton os3txt;
    private javax.swing.JRadioButton os4txt;
    private javax.swing.JRadioButton os5txt;
    private javax.swing.JRadioButton os6txt;
    private static javax.swing.JButton sem1button;
    private static javax.swing.JButton sem2button;
    public static javax.swing.JTextField yeartxt;
    // End of variables declaration//GEN-END:variables
}
