/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import nsbm.controller.paymentController;
import nsbm.model.payment;
/**
 *
 * @author Ravindu
 */
public class paymentInfo extends javax.swing.JFrame {

    /**
     * Creates new form paymentInfo
     */
    String subjects[] = {"0","0","0","0","0","0","0"};
    String pay[] = {"0","0","0","0","0","0","0"};
    public paymentInfo() {
        initComponents();
        showDate();
        yrtxt.setVisible(false);
        notxt.setVisible(false);
    }
    
    void showDate(){
        Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
            datetxt.setText(s.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gotID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sub2txt = new javax.swing.JTextField();
        sub3txt = new javax.swing.JTextField();
        sub4txt = new javax.swing.JTextField();
        sub5txt = new javax.swing.JTextField();
        sub6txt = new javax.swing.JTextField();
        sub7txt = new javax.swing.JTextField();
        pay1txt = new javax.swing.JTextField();
        pay2txt = new javax.swing.JTextField();
        pay3txt = new javax.swing.JTextField();
        pay4txt = new javax.swing.JTextField();
        pay5txt = new javax.swing.JTextField();
        pay6txt = new javax.swing.JTextField();
        pay7txt = new javax.swing.JTextField();
        sub1txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        totaltxt = new javax.swing.JTextField();
        yrtxt = new javax.swing.JTextField();
        notxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        gotID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButton1.setText("Payment Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gotID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gotID)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Subject");

        jLabel2.setText("payment (Rs.)");

        sub2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub2txtActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Payment");

        yrtxt.setText("jTextField1");

        notxt.setText("jTextField2");

        jButton2.setText("home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Enrollment Date");

        jButton3.setText("Enroll Payment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sub7txt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sub2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(101, 101, 101)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pay2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pay6txt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pay7txt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pay5txt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pay4txt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pay3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pay1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sub1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub4txt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub5txt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub6txt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(yrtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(88, 88, 88))))
            .addGroup(layout.createSequentialGroup()
                .addGap(527, 527, 527)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datetxt)
                    .addComponent(totaltxt, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(349, 349, 349))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sub2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pay2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sub3txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pay3txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sub4txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pay4txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yrtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sub5txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pay5txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addGap(10, 10, 10)
                .addComponent(notxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub6txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay6txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub7txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay7txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int i;
        
        if(RegisterExPostgrad.x == true){
            gotID.setText(RegisterExPostgrad.IDtxt.getText());
            yrtxt.setText(RegisterExPostgrad.yeartxt.getText().substring(0,1));
            notxt.setText(RegisterExPostgrad.numtxt.getText());
        }
        if(courseRegPostgraduate.x == true){
            gotID.setText(courseRegPostgraduate.IDtxt.getText());
            yrtxt.setText(courseRegPostgraduate.yeartxt.getText());
            notxt.setText(courseRegPostgraduate.numtxt.getText());
        }
        if(courseRegNew.x == true){
            gotID.setText(courseRegNew.IDtxt.getText());
            yrtxt.setText(courseRegNew.yeartxt.getText());
            notxt.setText(courseRegNew.numtxt.getText());
        }
        if(RegisterExUndergrad.x == true){
            gotID.setText(RegisterExUndergrad.IDtxt.getText());
            yrtxt.setText(RegisterExUndergrad.yeartxt.getText().substring(0,1));
            notxt.setText(RegisterExUndergrad.numtxt.getText());
        }
        
        try {
            String sql = "Select subjectID from subjectselection where StudentID = ? and subjectID like ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, gotID.getText());
            stm.setObject(2,"%"+yrtxt.getText()+notxt.getText()+"%");
            
            ResultSet rs = stm.executeQuery();
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
            if(rs.next()){
                //System.out.println(rs.getString("subjectID"));
                subjects[0] = rs.getString("subjectID");
            }
            if(rs.next()){
                subjects[1] = rs.getString("subjectID");
            }
            if(rs.next()){
                subjects[2] = rs.getString("subjectID");
            }
            if(rs.next()){
                subjects[3] = rs.getString("subjectID");
            }
            if(rs.next()){
                subjects[4] = rs.getString("subjectID");
            }
            if(rs.next()){
                subjects[5] = rs.getString("subjectID");
            }
            if(rs.next()){
                subjects[6] = rs.getString("subjectID");
            }

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        
        
        try {
            String sql = "Select subjectName,cost from subjects where subjectID = ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, subjects[0]);
            
            ResultSet rs = stm.executeQuery();
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
            while(rs.next()){
                sub1txt.setText(rs.getString("subjectName"));
                pay1txt.setText(rs.getString("cost"));
                pay[0] = rs.getString("cost");
            }
            

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        try {
            String sql = "Select subjectName,cost from subjects where subjectID = ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, subjects[1]);
            
            ResultSet rs = stm.executeQuery();
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
            while(rs.next()){
                sub2txt.setText(rs.getString("subjectName"));
                pay2txt.setText(rs.getString("cost"));
                pay[1] = rs.getString("cost");
            }
            

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        try {
            String sql = "Select subjectName,cost from subjects where subjectID = ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, subjects[2]);
            
            ResultSet rs = stm.executeQuery();
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
            while(rs.next()){
                sub3txt.setText(rs.getString("subjectName"));
                pay3txt.setText(rs.getString("cost"));
                pay[2] = rs.getString("cost");
            }
            

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        try {
            String sql = "Select subjectName,cost from subjects where subjectID = ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, subjects[3]);
            
            ResultSet rs = stm.executeQuery();
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
            while(rs.next()){
                sub4txt.setText(rs.getString("subjectName"));
                pay4txt.setText(rs.getString("cost"));
                pay[3] = rs.getString("cost");
            }
            

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        try {
            String sql = "Select subjectName,cost from subjects where subjectID = ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, subjects[4]);
            
            ResultSet rs = stm.executeQuery();
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
            while(rs.next()){
                sub5txt.setText(rs.getString("subjectName"));
                pay5txt.setText(rs.getString("cost"));
                pay[4] = rs.getString("cost");
            }
            

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        try {
            String sql = "Select subjectName,cost from subjects where subjectID = ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, subjects[5]);
            
            ResultSet rs = stm.executeQuery();
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
            while(rs.next()){
                sub6txt.setText(rs.getString("subjectName"));
                pay6txt.setText(rs.getString("cost"));
                pay[5] = rs.getString("cost");
            }
            

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        try {
            String sql = "Select subjectName,cost from subjects where subjectID = ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, subjects[6]);
            
            ResultSet rs = stm.executeQuery();
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
            while(rs.next()){
                sub7txt.setText(rs.getString("subjectName"));
                pay7txt.setText(rs.getString("cost"));
                pay[6] = rs.getString("cost");
            }
            

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        
        
        
        float pay1 = Float.parseFloat(pay[0]);
        float pay2 = Float.parseFloat(pay[1]);
        float pay3 = Float.parseFloat(pay[2]);
        float pay4 = Float.parseFloat(pay[3]);
        float pay5 = Float.parseFloat(pay[4]);
        float pay6 = Float.parseFloat(pay[5]);
        float pay7 = Float.parseFloat(pay[6]);
        
        float total = pay1+pay2+pay3+pay4+pay5+pay6+pay7;
        System.out.println(total);
        String Total = Float.toString(total);
        totaltxt.setText(Total);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        paymentInfo frame = new paymentInfo();
        home p = new home();
        p.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String id = gotID.getText();
        String year = yrtxt.getText();
        String sem = notxt.getText();
        String date = datetxt.getText();
        String amount = totaltxt.getText();
        payment p = new payment(id,year,sem,date,amount);
        
        try{
                String sql = "Delete from semesterenrollment where studentID =?";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
                PreparedStatement stm = conn.prepareStatement(sql);
                stm.setObject(1, id);
                

                int res = stm.executeUpdate();
                if(res>0){

                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        
        
        try {
            int res = paymentController.payment(p);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Enrollment Successfull!");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No Driver found");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sub2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub2txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paymentInfo().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField datetxt;
    public static javax.swing.JLabel gotID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JTextField notxt;
    private javax.swing.JTextField pay1txt;
    private javax.swing.JTextField pay2txt;
    private javax.swing.JTextField pay3txt;
    private javax.swing.JTextField pay4txt;
    private javax.swing.JTextField pay5txt;
    private javax.swing.JTextField pay6txt;
    private javax.swing.JTextField pay7txt;
    private javax.swing.JTextField sub1txt;
    private javax.swing.JTextField sub2txt;
    private javax.swing.JTextField sub3txt;
    private javax.swing.JTextField sub4txt;
    private javax.swing.JTextField sub5txt;
    private javax.swing.JTextField sub6txt;
    private javax.swing.JTextField sub7txt;
    private javax.swing.JTextField totaltxt;
    private static javax.swing.JTextField yrtxt;
    // End of variables declaration//GEN-END:variables
}
