/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static nsbm.paymentInfo.gotID;

/**
 *
 * @author Ravindu
 */
public class viewResults extends javax.swing.JFrame {

    /**
     * Creates new form viewResults
     */
    float marks[] = {0,0,0,0,0,0,0};
    String results[] = {"0","0","0","0","0","0","0"};
    public viewResults() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        yeartxt = new javax.swing.JTextField();
        semtxt = new javax.swing.JTextField();
        sub1txt = new javax.swing.JTextField();
        sub2txt = new javax.swing.JTextField();
        sub3txt = new javax.swing.JTextField();
        sub4txt = new javax.swing.JTextField();
        sub5txt = new javax.swing.JTextField();
        sub6txt = new javax.swing.JTextField();
        sub7txt = new javax.swing.JTextField();
        res2txt = new javax.swing.JTextField();
        res3txt = new javax.swing.JTextField();
        res4txt = new javax.swing.JTextField();
        res5txt = new javax.swing.JTextField();
        res6txt = new javax.swing.JTextField();
        res7txt = new javax.swing.JTextField();
        res1txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 882, 51);

        jLabel1.setText("Student ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 79, 52, 14);

        jLabel2.setText("Academic year");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 126, 70, 14);

        jLabel3.setText("Semester");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 188, 45, 14);
        getContentPane().add(idtxt);
        idtxt.setBounds(120, 76, 133, 20);
        getContentPane().add(yeartxt);
        yeartxt.setBounds(120, 123, 133, 20);
        getContentPane().add(semtxt);
        semtxt.setBounds(120, 185, 133, 20);
        getContentPane().add(sub1txt);
        sub1txt.setBounds(418, 76, 226, 20);
        getContentPane().add(sub2txt);
        sub2txt.setBounds(418, 123, 226, 20);

        sub3txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub3txtActionPerformed(evt);
            }
        });
        getContentPane().add(sub3txt);
        sub3txt.setBounds(418, 175, 226, 20);
        getContentPane().add(sub4txt);
        sub4txt.setBounds(418, 230, 226, 20);
        getContentPane().add(sub5txt);
        sub5txt.setBounds(418, 285, 226, 20);
        getContentPane().add(sub6txt);
        sub6txt.setBounds(418, 338, 226, 20);
        getContentPane().add(sub7txt);
        sub7txt.setBounds(418, 397, 226, 20);

        res2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res2txtActionPerformed(evt);
            }
        });
        getContentPane().add(res2txt);
        res2txt.setBounds(728, 123, 65, 20);
        getContentPane().add(res3txt);
        res3txt.setBounds(728, 175, 65, 20);
        getContentPane().add(res4txt);
        res4txt.setBounds(728, 230, 65, 20);
        getContentPane().add(res5txt);
        res5txt.setBounds(728, 285, 65, 20);
        getContentPane().add(res6txt);
        res6txt.setBounds(728, 338, 65, 20);
        getContentPane().add(res7txt);
        res7txt.setBounds(733, 397, 60, 20);
        getContentPane().add(res1txt);
        res1txt.setBounds(728, 76, 65, 20);

        jButton1.setText("View Results");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 360, 100, 23);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 360, 65, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sub3txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub3txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub3txtActionPerformed

    private void res2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res2txtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = idtxt.getText();
        String year = yeartxt.getText();
        String sem = semtxt.getText();
        int i;
        
        try {
            String sql = "Select subjectID,examMarks from subjectselection where StudentID = ? and subjectID like ? ";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm","root","");
            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setObject(1, id);
            stm.setObject(2,"%"+year+sem+"%");
            
            ResultSet rs = stm.executeQuery();
            //String comArr[] = {"0","0","0"};            //String x = "cs"+i+"txt";
            if(rs.next()){
                //System.out.println(rs.getString("subjectID"));
                sub1txt.setText(rs.getString("subjectID"));
                String res1 = rs.getString("examMarks");
                float r1 = Float.parseFloat(res1);
                marks[0] = r1;
            }
            if(rs.next()){
                sub2txt.setText(rs.getString("subjectID"));
                String res2 = rs.getString("examMarks");
                float r2 = Float.parseFloat(res2);
                marks[1] = r2;
            }
            if(rs.next()){
                sub3txt.setText(rs.getString("subjectID"));
                String res3 = rs.getString("examMarks");
                float r3 = Float.parseFloat(res3);
                marks[2] = r3;
            }
            if(rs.next()){
                sub4txt.setText(rs.getString("subjectID"));
                String res4 = rs.getString("examMarks");
                float r4 = Float.parseFloat(res4);
                marks[3] = r4;
            }
            if(rs.next()){
                sub5txt.setText(rs.getString("subjectID"));
                String res5 = rs.getString("examMarks");
                float r5 = Float.parseFloat(res5);
                marks[4] = r5;
            }
            if(rs.next()){
                sub6txt.setText(rs.getString("subjectID"));
                String res6 = rs.getString("examMarks");
                float r6 = Float.parseFloat(res6);
                marks[5] = r6;
            }
            if(rs.next()){
                sub7txt.setText(rs.getString("subjectID"));
                String res7 = rs.getString("examMarks");
                float r7 = Float.parseFloat(res7);
                marks[6] = r7;
            }

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        for(i=0;i<7;i++){
            float a = marks[i];
            if(a>=85){
                results[i] = "A+";
            }
            else if(a>=80){
                results[i] = "A";
            }
            else if(a>=75){
                results[i] = "A-";
            }
            else if(a>=70){
                results[i] = "B+";
            }
            else if(a>=65){
                results[i] = "B";
            }
            else if(a>=60){
                results[i] = "B-";
            }
            else if(a>=55){
                results[i] = "C+";
            }
            else if(a>=50){
                results[i] = "C";
            }
            else if(a>=45){
                results[i] = "C-";
            }
            else if(a>=40){
                results[i] = "D+";
            }
            else if(a>=35){
                results[i] = "D";
            }
            else if(a>=30){
                results[i] = "D-";
            }
            else if(a==0){
                results[i] = null;
            }
            else {
                results[i] = "F";
            }
        }
        
        res1txt.setText(results[0]);
        res2txt.setText(results[1]);
        res3txt.setText(results[2]);
        res4txt.setText(results[3]);
        res5txt.setText(results[4]);
        res6txt.setText(results[5]);
        res7txt.setText(results[6]);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        viewResults frame = new viewResults();
        home p =  new home();
        p.setVisible(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField res1txt;
    private javax.swing.JTextField res2txt;
    private javax.swing.JTextField res3txt;
    private javax.swing.JTextField res4txt;
    private javax.swing.JTextField res5txt;
    private javax.swing.JTextField res6txt;
    private javax.swing.JTextField res7txt;
    private javax.swing.JTextField semtxt;
    private javax.swing.JTextField sub1txt;
    private javax.swing.JTextField sub2txt;
    private javax.swing.JTextField sub3txt;
    private javax.swing.JTextField sub4txt;
    private javax.swing.JTextField sub5txt;
    private javax.swing.JTextField sub6txt;
    private javax.swing.JTextField sub7txt;
    private javax.swing.JTextField yeartxt;
    // End of variables declaration//GEN-END:variables
}
